version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-saas
    image: hyperf/hyperf:latest
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9701:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
#    tty: true
    command: >
      sh -c "
      git config --global --add safe.directory /opt/www &&
      php /opt/www/bin/hyperf.php server:watch"

networks:
  default:
    name: hyperf-skeleton
